language: ruby
bundler_args: "--without production"
env:
- RAILS_ENV=test DEVISE_JWT_SECRET_KEY=DEVISE_JWT_SECRET_KEY DEVISE_SECRET_KEY=DEVISE_SECRET_KEY
cache: bundler
jdk:
  - openjdk8
addons:
  postgresql: 10
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - libsodium-dev
before_install:
- nvm install 11.15.0
before_script:
- mkdir -p log
- cp config/travis/database.yml config/
- cp config/travis/sunspot.yml config/
- cp config/travis/mailers.yml config/
- mkdir -p solr/data/test
- mkdir -p solr/cores/test
- cp config/travis/core.properties solr/cores/test/
- npm install
script:
- bundle exec rake sunspot:solr:start
- bundle exec rails db:drop
- bundle exec rails db:create
- bundle exec rails db:migrate
- bundle exec rspec spec
- npm run test:all
services:
- postgresql
branches:
- travisci
- maint_1.3
- maint_1.4
- maint_1.5
- maint_1.6
- development
- development_v2
- master
notifications:
  slack:
    rooms:
      secure: fBO6yW1muuxvopaCn5mvNC5OtcEaXIv/EMQr+VHlHI40JqgfDeqwezdGlqXP+XVw6MyKJ3eKEFu6Komgjz01DB7Hr9pyT3x/26mderFPV5FGj8Dftnj3E19kgoSAkONE4E/msU3Th8cQfSqGY74yYxZDnE0fnzbUaDit9KPJsWS4Jztc51gmCvFcov0pNIz2o5V45jNRd5XFwe/F8rBgmegr5grPl7D802hKzuI5WFvNvmtOSiS0+pMTE6PZRg2slo2u8PgC3zRx74Dt4vndg8XtwH9PQmJwwDsB2rIFOdvntPxoAwtzMUk1AvU8IMUmdZTYsPcf0rOQHjzrko+p6oz/ZoekDmzArc/OEcqmM1OvGWjI3FM+5pWS5Cnb9yP0/6d2tqsgEoTEz772sykVn0iZ0Fvyo73HlFIsq6USj8QEeU6xAG6TMb32Qez7dB9baXWxjVBj9QXVE4MTVzb5EBeB56lBmSpWV1/wVSYsQOdPRoObiK+B9YxahhZ0Y27hWQOHVIQ7ct22MzqriPB6ISN9kUmvNGAzktFINX4LtS6InzSzTqjwuWHMlToE+4B3KF4hQk426muvEhEYi2DJaiO2gGh5E7MR6mQt1vET190IZ8Y87tHZ6MuGdpP6/qEsAQxEFZUZhuWv18cfYpvXevWeZt5a8M5HseGe5RUQvb4=
    template:
    - 'Test run completed for %{repository}/*%{branch}*: <%{build_url}|%{message}> Run duration: %{elapsed_time}'
