---
- name: 'Fedora :: install dnf-plugins-core'
  package:
    name: 'dnf-plugins-core'
    state: 'present'
  become: yes

- name: 'Fedora :: install Docker RPM repository'
  command: |
    dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    warn: no
  become: yes

- name: 'Fedora :: install Docker'
  package:
    name: 'docker-ce'
    state: 'present'
  become: yes
