apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.local.yml
      -o kompose/
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: solr
  name: solr
spec:
  ports:
  - name: "8983"
    port: 8983
    targetPort: 8983
  selector:
    io.kompose.service: solr
status:
  loadBalancer: {}
